### ISSUE TITLE
[1.17.1] This mod Conflicts with StepUp mod

### ISSUE THREAD

**Issue by deftesthawk** [ChloeDawn/BeaconOverhaul#14]
**Describe the bug**
When I install this with the mod StepUp it stops that mod from working, so I won't automatically step up blocks

**Reproduction steps**
Install BeaconOverhaul with StepUp mod

**Expected behavior**
StepUp will show up as enabled in chat but won't work when trying to go up a block

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Minecraft version: 1.17.1
 - Loader version: fabric-api-0.37.2+1.17
 - Mod version: BeaconOverhaul-1.4.1+1.17 
 - Mod version: stepup-1.17.1-fabric0.36.1-1.1
 
**Additional context**
N/A

**Comment by ChloeDawn** [comment]
Step height is now only changed when the jump boost effect is applied and removed, which should reduce this conflict.

https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.4.2+1.17 https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3476553

Unfortunately, there is no way to mitigate the conflict entirely due to the nature of the game.
