### ISSUE TITLE
Slow falling cancelation

### ISSUE THREAD

**Issue by Artic467** [ChloeDawn/BeaconOverhaul#25]
Playing in 1.19.1 when crouching the player still falls at the slower speed unlike what is stated in the description.

**Comment by Artic467** [comment]
It does seem to work when the elytra is activated.

**Comment by ChloeDawn** [comment]
Fixed in **1.7.3+1.19.2** [ [GitHub](https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.7.3+1.19.2) | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3983948) | [Modrinth](https://modrinth.com/mod/beaconoverhaul/version/1.7.3+1.19.2) ] and **1.6.1+1.18.2** [ [GitHub](https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.6.1+1.18.2) | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3983955) | [Modrinth](https://modrinth.com/mod/beaconoverhaul/version/1.6.1+1.18.2) ]
