### ISSUE TITLE
Haste IV not Applied w/ Netherite

### ISSUE THREAD

**Issue by heymanMC** [ChloeDawn/BeaconOverhaul#26]
**Describe the Bug:**
On a netherite beacon, max level Haste is not being applied. It instead applies Haste III, even though the tooltip says Haste IV.

**Reproduction Steps:**
1. Build netherite beacon.
2. Place beacon down.
3. Click Haste III in "Primary Power".
4. Click Haste IV in "Secondary Power".
5. Place ingot and click checkmark to apply.

**Expected Behavior:**
Haste IV should be applied. Instead, Haste III is applied.

**Screenshots:**
![image](https://user-images.githubusercontent.com/38384673/184945871-46d7056c-a93d-47c3-98da-ed917c5dac3d.png)

![image](https://user-images.githubusercontent.com/38384673/184945889-77874352-5c9a-46fa-80f5-0e40fdadaad1.png)

**Environment:**
 - Minecraft version: 1.19.1
 - Loader version: fabric 0.14.9
 - Mod version: 1.7.2+1.19.1
 - Other mods: None

**Comment by ChloeDawn** [comment]
Fixed in **1.7.3+1.19.2** [ [GitHub](https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.7.3+1.19.2) | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3983948) | [Modrinth](https://modrinth.com/mod/beaconoverhaul/version/1.7.3+1.19.2) ] and **1.6.1+1.18.2** [ [GitHub](https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.6.1+1.18.2) | [CurseForge](https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul/files/3983955) | [Modrinth](https://modrinth.com/mod/beaconoverhaul/version/1.6.1+1.18.2) ]
