### ISSUE TITLE
Wrong scaling of effect levels in diamond and below beacons.

### ISSUE THREAD

**Issue by ghost** [ChloeDawn/BeaconOverhaul#29]
Describe the bug:

When I was testing beacons tier with this mod, an iron beacon applies Haste III as a secondary power instead of Haste II.
With a diamond beacon happens the same, instead of Haste III it gives Haste IV.
Though secondary powers like regeneration scale fine.

Reproduction steps:

1. Build a full iron and diamond beacon.
2. Primary power: Click Haste I in iron beacon, Haste II in diamond beacon.
3. Secondary power: Click Haste II in iron beacon, Haste III in diamond beacon.

Expected behavior:

Obtain Haste II in iron beacon, instead you get Haste III.
Obtain Haste III in diamond beacon, instead you get Haste IV.

Screenshots:

Iron Beacon
![Ir  1](https://user-images.githubusercontent.com/126512959/221673153-dac63108-9f12-473b-acb1-19eddcdba36b.png)
![Ir  2](https://user-images.githubusercontent.com/126512959/221673536-c8590337-f152-4460-8c85-2fd84f8552e1.png)

Diamond Beacon
![Di  1](https://user-images.githubusercontent.com/126512959/221673600-2f4ae4ba-442a-4f0a-9eb1-fa0b100b9e79.png)
![Di  2](https://user-images.githubusercontent.com/126512959/221673608-9dc06653-0c25-4c71-af84-b4f2a0b659be.png)

Environment:

 - Minecraft version: 1.19.3
 - Loader version fabric 0.14.14
 - Mod version 1.7.5+1.19.3
 - Other mods: None

**Comment by DocAndrei** [comment]
Same in 1.8.2+1.20

**Comment by ChloeDawn** [comment]
Fixed in [1.7.7+1.19.4](https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.7.7%2B1.19.4) ([CurseForge](https://curseforge.com/minecraft/mc-mods/beaconoverhaul/files/4715715), [Modrinth](https://modrinth.com/mod/beaconoverhaul/version/1.7.7+1.19.4)) and [1.8.4+1.20](https://github.com/ChloeDawn/BeaconOverhaul/releases/tag/1.8.4%2B1.20) ([CurseForge](https://curseforge.com/minecraft/mc-mods/beaconoverhaul/files/4715716), [Modrinth](https://modrinth.com/mod/beaconoverhaul/version/1.8.4+1.20))
